version: '3'
services:
    app:
        build:
            context: .
        container_name: laravel-app
        volumes:
            - .:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        ports:
            - "8000:8000"
        environment:
            # Variables de entorno de Laravel
            APP_NAME: Laravel
            APP_ENV: local
            APP_KEY: base64:D28Fwg02L3sY72DY7B/2yiPVCO3d2Tn5oAwZdAgRtew=
            APP_DEBUG: 'true'
            API_ENDPOINT: http://fastapi-container:8001/api/clustering/create-pycaret-clusters

            DB_CONNECTION: sqlite
            DB_DATABASE: /var/www/database/database.sqlite
            CACHE_DRIVER: file
            SESSION_DRIVER: file
            QUEUE_DRIVER: sync
        networks:
            - shared_network

    nginx:
        image: nginx:alpine
        container_name: nginx-laravel
        volumes:
            - .:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        networks:
            - shared_network
        depends_on:
            - app

networks:
    shared_network:
        name: shared_network
        driver: bridge
